src/Entity/Property.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use App\Repository\PropertyRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Component\Validator\Constraints\RegexValidator;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 */
class Property
{
    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];

    public function __construct() {
        $this->created_at = new \DateTime();
    }

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "Your first name must be at least {{ limit }} characters long",
     *      maxMessage = "Your first name cannot be longer than {{ limit }} characters",
     *      allowEmptyString = false
     * )
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @Assert\NotBlank(message="Not be blank.")
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @Assert\NotBlank(message="Not be blank.")
     * @Assert\Regex(
     *   pattern     = "/^[0-9]{5}$/i",
     *   htmlPattern = "^[0-9]{5}$",
     *   message="ERROR"
     * )
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $badRooms;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        $slugify = new Slugify();
        $slug =  $slugify->slugify($this->title);
        return $slug;
    }


    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getformatedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getBadRooms(): ?int
    {
        return $this->badRooms;
    }

    public function setBadRooms(int $badRooms): self
    {
        $this->badRooms = $badRooms;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('badRooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            ->add('city')
            ->add('address')
            ->add('postalCode')
            ->add('sold')
            //->add('created_at')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domaine' => 'forms'
        ]);
    }

    private function getChoices()
    {
        $choices = Property::HEAT;
        $output = [];
        foreach($choices as $key => $value) {
            $output[$value] = $key;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Property;
use App\Repository\PropertyRepository;
use Doctrine\Persistence\ObjectManager;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController {

    /**
    * @var PropertyRepository
    */
    private $repository;

    /**
    * @var ObjectManager 
    */
    private $em;

    public function __construct(PropertyRepository $Repository, ObjectManager $Em) {
        $this->repository = $Repository;
        $this->em = $Em;
    }

    /**
     * @Route("biens", name="property.index")
     * @param Property $property
     * @return Response
     */
    public function index () :Response {
        
        /* 1
        $property = new Property();
        $property->setTitle('Mon premier bien')
            ->setPrice(200000)
            ->setRooms(4)
            ->setBadRooms(3)
            ->setDescription('...desc')
            ->setSurface(60)
            ->setFloor(4)
            ->setHeat(1)
            ->setCity('Namur')
            ->setAddress('55 Henri Lecocq')
            ->setPostalCode('5000');
        $em = $this->getDoctrine()->getManager();
        $em->persist($property);
        $em->flush(); */

        /* 2
        $repository = $this->getDoctrine()->getRepository(Property::class);
        dump($repository);
        */

        /* 3 
        //$property = $this->repository->find(1); // recupère le record à l'id 1
        //$property = $this->repository->findAll(); // recupère un tableau avec tous les record de la table property
        //$property = $this->repository->findOneBy(['floor' => 4]); // récupère tous les records ou floor = 4
        $property = $this->repository->findAllVisible(); // methode personnalisé dans PropertyRepository 
        dump($property);
        $property[0]->setSold(true);
        $this->em->flush();
        */
        return $this->render('pages/property/index.html.twig',
            [ 'current_menu' => 'property']);
    }

    /**
     * @Route("/biens/{slug}-{id}", name="property.show", requirements ={ "slug": "[a-z0-9\-]*" })
     * @param Property $property
     * @return Response
     */
    public function show (Property $property, string $slug) :Response 
    {
        if($property->getSlug() !== $slug) {
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ], 301);
        }

        return $this->render('pages/property/show.html.twig',[   
                'property' => $property,
                'current_menu' => 'property.show'
            ]);
    }
}

templates/pages/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Tous nos Biens' %}

{% block body %}
    <div class="container mt-4">
        <h1>Tous nos Biens</h1>
        <p>Deserunt ea do labore nisi cupidatat irure do eu incididunt ipsum eiusmod reprehenderit ea. Et voluptate tempor occaecat cupidatat. Et excepteur esse laboris cillum officia minim tempor officia. Minim qui veniam duis culpa tempor eiusmod eiusmod exercitation officia excepteur labore labore excepteur. Est do incididunt ipsum dolor in duis est qui voluptate Lorem pariatur irure. Officia amet qui dolore nostrud proident magna pariatur mollit ut tempor mollit deserunt. Consequat nulla non Lorem est deserunt esse amet consectetur ut.</p>
    </div>
{% endblock %}

templates/pages/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title property.title %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-8" >
                </div>
                <div class="col-md-4" >
                    <h2>{{ property.title }}</h2>
                    <h3>{{ property.rooms }} pièces ) {{ property.surface }} m2</h3>
                    <div class="text-primary" style="font-size: 3em; font-weight: bold;">
                        {{ property.formatedPrice}}
                    </div>
                    <a href="#" class="btn btn-primary">Contacter l'agence</a>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-4">
            <p>
                {{ property.description | nl2br }}
            </p>

            <div class="row" >
                <div class="col-md-8" >
                    <h2>Caractéristiques : </h2>
                    <table class="table table-striped">
                        <tr>
                            <td>Surface habitable</td>
                            <td>{{ property.surface }}</td>
                        </tr>
                        <tr>
                            <td>Pièces</td>
                            <td>{{ property.rooms }}</td>
                        </tr>
                         <tr>
                            <td>Chambres</td>
                            <td>{{ property.badRooms }}</td>
                        </tr>
                        <tr>
                            <td>Etage</td>
                            <td>{{ property.floor}}</td>
                        </tr>
                        <tr>
                            <td>Chauffage</td>
                            <td>{{ property.heatType}}</td>
                        </tr>
                    </table>
                </div>

                <div class="col-md-4"  >
                    <h2>Spécificités : </h2>
                </div>
            </div>
    </div>
{% endblock %}